import type { ChatMessage } from './types'

/** Longest the quoted customer message runs before we ellipsize it —
 *  keeps the internal note to a glanceable one-liner. */
const MAX_QUOTE_LEN = 160

/**
 * Deterministic, customer-facing message sent when the bot hands a
 * thread off to a human — NEVER generated by the LLM (no extra call, no
 * risk of it inventing a timeframe or a detail we don't actually know).
 * Deliberately vague on timing ("En breve") since we have no real ETA to
 * offer. Lives here (not messages/en.json or ko.json) because it's part
 * of the AI/handoff engine's behavior sent to the *customer*, not UI
 * chrome rendered for the viewing agent — i18n would localize it to the
 * wrong audience (the agent's locale, not the customer's).
 */
export const HANDOFF_CUSTOMER_NOTICE =
  'Para ayudarte correctamente con esta consulta, voy a derivarte con uno de nuestros asesores. En breve continuarán la atención contigo por este medio.'

/**
 * Build the short internal note the auto-reply bot leaves on a
 * conversation when it hands off to a human. Deterministic — composed
 * from context we already have (no extra LLM call / token spend), so it
 * can't fail or add latency to the handoff.
 *
 * Reads as, e.g.:
 *   "🤖 AI agent handed off after 2 replies. Last customer message:
 *    “can I speak to a manager about my refund?”"
 * or, when triggered by the reply cap:
 *   "🤖 AI agent handed off after reaching the 3-reply limit. Last
 *    customer message: “…”"
 *
 * `replyCount` is the bot's auto-reply tally for the thread (0 when it
 * bailed on the very first inbound without answering). `reason` picks
 * the base sentence: `'model'` (default) is the LLM choosing to hand off
 * (or failing to answer); `'cap'` is the deterministic reply-cap path,
 * which never calls the model at all — the wording must not claim it did.
 */
export function buildHandoffSummary(args: {
  messages: ChatMessage[]
  replyCount: number
  reason?: 'model' | 'cap'
  /** Required context for `reason: 'cap'` — the configured limit that was hit. */
  maxReplies?: number
}): string {
  const { messages, replyCount, reason = 'model', maxReplies } = args

  const lastCustomer = [...messages]
    .reverse()
    .find((m) => m.role === 'user' && m.content.trim())

  const base =
    reason === 'cap'
      ? `🤖 AI agent handed off after reaching the ${maxReplies ?? replyCount}-reply limit.`
      : (() => {
          const replies =
            replyCount === 0
              ? 'without replying'
              : `after ${replyCount} ${replyCount === 1 ? 'reply' : 'replies'}`
          return `🤖 AI agent handed off ${replies}.`
        })()

  if (!lastCustomer) return base

  const quote = truncate(lastCustomer.content.trim(), MAX_QUOTE_LEN)
  return `${base} Last customer message: “${quote}”`
}

function truncate(text: string, max: number): string {
  const collapsed = text.replace(/\s+/g, ' ')
  if (collapsed.length <= max) return collapsed
  return `${collapsed.slice(0, max - 1).trimEnd()}…`
}
